### PR TITLE
Workflows cleanup: use secrets directly and dedupe test runs

### LINKED ISSUE #143: What is the `Testing` deployment environment for?
I notice that when I push to a PR branch, it triggers some kind of build of this `Testing` "Deployment"...
Screenshot 2024-05-06 at 1 03 17 PM
Screenshot 2024-05-06 at 1 02 46 PM

what is this and why do we need it? 😃

### PR DESCRIPTION
**Pull request by cisaacstern**
Closes #143

This PR cleans up our CI testing / workflows developer experience in two ways:
1. Removes use of a namespaced Deployment "environment" for holding our GitHub Secrets in favor of using the global GitHub Secrets namespace directly. This aligns us with the most common usage pattern for testing CI wherein the test checks are nested under a collapsible status icon associated with a _commit_, and there is not (as we currently have) a cluttering of the (non-collapsible) PR history with Deployments notifications (as shown in the screenshot in #143).
2. Also I've changed the triggering rules to de-duplicate test runs for PRs: currently we are getting a run for the commit to the PR _and_ a duplicate run for the push to the branch from which the PR originates. By changing the rule to only trigger test runs on pushes to the default branch name, this duplication will be avoided.

Note: To get CI to work with this new secrets configuration, we will need to recreate the Testing Deployment Secrets as Repository Secrets, on https://github.com/wildlife-dynamics/ecoscope/settings/secrets/actions, here:
Screenshot 2024-05-08 at 11 58 36 AM
For probably good security reasons, we can't move existing secrets, so they will need to be re-added by someone who has access to the original secrets.

### CODE REVIEW

**Comment by cisaacstern** [comment]
> and there is not (as we currently have) a cluttering of the (non-collapsible) PR history with Deployments notifications 

Now that CI has run here, we can see this in action:
| This PR | #138 |
| ------- | ---- |
| Screenshot 2024-05-08 at 12 05 51 PM | Screenshot 2024-05-08 at 12 06 07 PM |

So if I may be so bold ...

image

**Comment by cisaacstern** [comment]
I assume windows tests are failing because, as @atmorling mentioned at standup today, windows throws an error if EarthEngine credentials are not available, and we haven't yet recreated the test secrets as Repository Secrets. Once that's done, we can re-run tests to confirm.

**Review by atmorling — APPROVED** [review]
Sounds good - looks good.
@ericgitonga Would you have the original credentials set up in the Testing environment?

**Comment by ericgitonga** [comment]
> Sounds good - looks good. @ericgitonga Would you have the original credentials set up in the Testing environment?

I have the creds I use on my local... For original creds, let me check on those.

**Comment by cisaacstern** [comment]
Thanks @ericgitonga !

**Comment by atmorling** [comment]
@ericgitonga since #129 exists I guess the original creds were linked to someone's personal account.

**Comment by ericgitonga** [comment]
> > @ericgitonga since #129 exists I guess the original creds were linked to someone's personal account.
> 
> Yes indeed. Peter Kulits was the one who first came up with this, so we'd have to check with him for those. I've asked him and await his response.

I have emailed to you both (on your earthranger accounts) the info from Peter.

**Comment by atmorling** [comment]
I've gone ahead and added the credentials to the repo secrets

**Comment by atmorling** [comment]
I've also updated the branch protection rules as they required a successful 'deployment' which is no longer relevant with this change

**Pull request merged**
